# Generated by Django 4.1 on 2022-08-31 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='featured_image',
            field=models.ImageField(default='recipe/dinner-02.jpg', upload_to='recipe/'),
        ),
    ]
