# Generated by Django 4.1 on 2022-08-30 16:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quick_Idea',
            fields=[
                ('title', models.CharField(default='Quick Idea... Check it Out!', max_length=1000)),
                ('alt', models.CharField(default='Quick Idea Image', max_length=50)),
                ('img', models.ImageField(upload_to='quick_ideas/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.profile')),
            ],
        ),
    ]
