# Generated by Django 4.1 on 2022-08-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quick_idea',
            name='url_name',
            field=models.CharField(default='page-home', max_length=100),
        ),
    ]
