# Generated by Django 4.1 on 2022-08-30 17:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('pages', '0002_quick_idea_url_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featured_Recipe',
            fields=[
                ('title', models.CharField(default='Featured Recipe...', max_length=255)),
                ('body', models.CharField(default='Featured Body text...', max_length=500)),
                ('img', models.ImageField(upload_to='featured_recipe/')),
                ('alt', models.CharField(default='Alt text', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.profile')),
            ],
        ),
    ]
