# Generated by Django 4.1 on 2022-08-30 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='featured_image',
            field=models.ImageField(default='article/dinner-01.jpg', upload_to='article/'),
        ),
    ]
