# Generated by Django 4.1 on 2022-09-02 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_image',
            name='alt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='article_video',
            name='alt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
