# Generated by Django 4.1 on 2022-09-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_image_alt_article_video_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='featured_image',
            field=models.ImageField(upload_to='article/'),
        ),
    ]
