# Generated by Django 4.1 on 2022-09-02 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='alt_image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
